# Generated by Django 5.2.5 on 2025-09-16 15:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('currency', models.CharField(choices=[('XAF', 'FCFA (XAF)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dollar (USD)')], default='XAF', max_length=4, verbose_name='Devise')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Validé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=10, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction financière',
                'verbose_name_plural': 'Transactions financières',
                'ordering': ['-created_at'],
            },
        ),
    ]
