# Generated by Django 5.2.1 on 2025-09-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
