# Generated by Django 5.2.5 on 2025-09-18 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_userpermission'),
        ('rh', '0002_remove_leaverequest_employee_delete_employeeprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poste')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('contract_type', models.CharField(blank=True, choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Alternance', 'Alternance'), ('Freelance', 'Freelance')], max_length=20, null=True, verbose_name='Type de contrat')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('paid', 'Congé payé'), ('unpaid', 'Congé sans solde'), ('sick', 'Congé maladie'), ('maternity', 'Congé maternité'), ('paternity', 'Congé paternité')], max_length=20, verbose_name='Type de congé')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motif')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Mois')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire de base')),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Primes')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Déductions')),
                ('total_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire net')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(verbose_name="Date d'évaluation")),
                ('period_start', models.DateField(verbose_name='Début de période')),
                ('period_end', models.DateField(verbose_name='Fin de période')),
                ('overall_rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Note globale')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du poste')),
                ('description', models.TextField(verbose_name='Description')),
                ('requirements', models.TextField(verbose_name='Prérequis')),
                ('location', models.CharField(max_length=100, verbose_name='Lieu')),
                ('job_type', models.CharField(choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('contract', 'Contrat'), ('internship', 'Stage')], max_length=20, verbose_name='Type de poste')),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fourchette salariale')),
                ('posted_date', models.DateField(auto_now_add=True, verbose_name='Date de publication')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='Date de clôture')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Fermé'), ('filled', 'Pourvu')], default='open', max_length=20, verbose_name='Statut')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
            ],
        ),
    ]
