# Generated by Django 5.2.1 on 2025-09-17 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('ip', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('device', models.CharField(max_length=255, verbose_name='Appareil')),
                ('type_action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('FAILED', 'Échec de connexion')], max_length=50, verbose_name="Type d'action")),
                ('error', models.CharField(blank=True, max_length=255, null=True, verbose_name="Message d'erreur")),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_connexion', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Log de connexion',
                'verbose_name_plural': 'Logs de connexion',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='PointageHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date de pointage')),
                ('heure_arrivee', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('heure_depart', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-date', '-heure_arrivee'],
                'unique_together': {('employe', 'date')},
            },
        ),
    ]
