# Generated by Django 5.2.1 on 2025-09-17 10:45

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_Horraire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresHoraires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut_standard', models.TimeField(default=datetime.time(9, 0), verbose_name='Heure de début standard')),
                ('heure_fin_standard', models.TimeField(default=datetime.time(17, 0), verbose_name='Heure de fin standard')),
                ('marge_retard', models.IntegerField(default=15, help_text='Temps de grâce avant de considérer un retard', verbose_name='Marge de retard (minutes)')),
                ('temps_pause_dejeuner', models.IntegerField(default=60, verbose_name='Temps de pause déjeuner (minutes)')),
                ('jours_travailles', models.JSONField(default=dict, help_text='Configuration des jours travaillés (1=Lundi, 7=Dimanche)', verbose_name='Jours travaillés')),
            ],
            options={
                'verbose_name': 'Paramètres des horaires',
                'verbose_name_plural': 'Paramètres des horaires',
            },
        ),
        migrations.AddField(
            model_name='logconnexion',
            name='details',
            field=models.JSONField(blank=True, help_text='Stockage de données supplémentaires au format JSON', null=True, verbose_name='Détails'),
        ),
        migrations.AddField(
            model_name='logconnexion',
            name='success',
            field=models.BooleanField(default=True, verbose_name='Succès'),
        ),
        migrations.AddField(
            model_name='pointagehoraire',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='pointagehoraire',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'En retard'), ('CONGE', 'En congé')], default='ABSENT', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='logconnexion',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Appareil'),
        ),
        migrations.AlterField(
            model_name='logconnexion',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AlterField(
            model_name='logconnexion',
            name='type_action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('FAILED', 'Échec de connexion'), ('POINTAGE_ARRIVEE', 'Pointage arrivée'), ('POINTAGE_DEPART', 'Pointage départ')], max_length=50, verbose_name="Type d'action"),
        ),
        migrations.AddIndex(
            model_name='logconnexion',
            index=models.Index(fields=['employe', 'date_heure'], name='gestion_Hor_employe_104afb_idx'),
        ),
        migrations.AddIndex(
            model_name='logconnexion',
            index=models.Index(fields=['type_action'], name='gestion_Hor_type_ac_7257e7_idx'),
        ),
        migrations.AddIndex(
            model_name='pointagehoraire',
            index=models.Index(fields=['employe', 'date'], name='gestion_Hor_employe_3b0e10_idx'),
        ),
        migrations.AddIndex(
            model_name='pointagehoraire',
            index=models.Index(fields=['status'], name='gestion_Hor_status_2c60d6_idx'),
        ),
    ]
