# Generated by Django 5.2.1 on 2025-09-17 17:53

from django.db import migrations
from django.utils import timezone

def set_default_jours_travailles(apps, schema_editor):
    ParametresHoraires = apps.get_model('gestion_Horraire', 'ParametresHoraires')
    for param in ParametresHoraires.objects.all():
        if not param.jours_travailles:
            param.jours_travailles = {"1": True, "2": True, "3": True, "4": True, "5": True, "6": False, "7": False}
            param.save()

def reverse_set_default_jours_travailles(apps, schema_editor):
    # No reverse operation needed
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('gestion_Horraire', '0002_parametreshoraires_logconnexion_details_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_jours_travailles, reverse_set_default_jours_travailles),
    ]
