# Generated by Django 5.2.1 on 2025-09-17 17:54

from django.db import migrations
from django.utils import timezone

def default_jours_travailles():
    return {"1": True, "2": True, "3": True, "4": True, "5": True, "6": False, "7": False}

def update_jours_travailles_default(apps, schema_editor):
    ParametresHoraires = apps.get_model('gestion_Horraire', 'ParametresHoraires')
    for param in ParametresHoraires.objects.all():
        if not param.jours_travailles:
            param.jours_travailles = default_jours_travailles()
            param.save()

def reverse_update_jours_travailles_default(apps, schema_editor):
    # No reverse operation needed
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('gestion_Horraire', '0003_auto_20250917_1853'),
    ]

    operations = [
        migrations.RunPython(update_jours_travailles_default, reverse_update_jours_travailles_default),
    ]
