# Generated by Django 5.2.1 on 2025-09-17 17:55

import datetime
import django.db.models.deletion
import gestion_Horraire.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_Horraire', '0004_auto_20250917_1854'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametreshoraires',
            options={'verbose_name': 'Paramètres horaires', 'verbose_name_plural': 'Paramètres horaires'},
        ),
        migrations.AddField(
            model_name='pointagehoraire',
            name='duree_travail_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Stockée pour les rapports', verbose_name='Durée de travail (minutes)'),
        ),
        migrations.AlterField(
            model_name='logconnexion',
            name='date_heure',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logconnexion',
            name='details',
            field=models.JSONField(blank=True, help_text='Stockage de données supplémentaires au format JSON', null=True),
        ),
        migrations.AlterField(
            model_name='logconnexion',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logconnexion',
            name='employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_connexion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logconnexion',
            name='error',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logconnexion',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logconnexion',
            name='success',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='logconnexion',
            name='type_action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('FAILED', 'Échec de connexion'), ('POINTAGE_ARRIVEE', 'Pointage arrivée'), ('POINTAGE_DEPART', 'Pointage départ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='parametreshoraires',
            name='heure_debut_standard',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='parametreshoraires',
            name='heure_fin_standard',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='parametreshoraires',
            name='jours_travailles',
            field=models.JSONField(default=gestion_Horraire.models.default_jours_travailles, help_text='1=Lundi, 7=Dimanche'),
        ),
        migrations.AlterField(
            model_name='parametreshoraires',
            name='marge_retard',
            field=models.IntegerField(default=15, help_text='Temps de grâce avant de considérer un retard (minutes)'),
        ),
        migrations.AlterField(
            model_name='parametreshoraires',
            name='temps_pause_dejeuner',
            field=models.IntegerField(default=60, help_text='Durée de la pause déjeuner (minutes)'),
        ),
    ]
